version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
        aliases:
          - fluentd


  elasticsearch:
    image: elasticsearch:6.6.1
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
        aliases:
          - elasticsearch

  kibana:
    image: kibana:6.6.1
    ports:
      - "5601:5601"
    networks:
      back_net:
        aliases:
          - kibana
      front_net:
        aliases:
          - kibana

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24